providers = []

[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]
aptPkgs = ["libcairo2-dev", "libpango1.0-dev", "libjpeg-dev", "libgif-dev", "librsvg2-dev", "libpixman-1-dev", "pkg-config", "python3", "build-essential"]

[phases.install]
cmds = ["cd central-server && npm install --include=dev"]

[phases.build]
cmds = ["cd central-server && npm run build"]

[start]
cmd = "cd central-server && npm start"
